export BUILT_PRODUCTS_DIR="/Users/xinsun/Library/Developer/Xcode/DerivedData/XSTests-cmkzjtilcohrtgdkssdfsfinnpne/Build/Products/Debug-iphonesimulator"
export NATIVE_ARCH="i386"
export OBJECT_FILE_DIR_normal="/Users/xinsun/Library/Developer/Xcode/DerivedData/XSTests-cmkzjtilcohrtgdkssdfsfinnpne/Build/Intermediates/XSTests.build/Debug-iphonesimulator/XSTests.build/Objects-normal"
export OBJROOT="/Users/xinsun/Library/Developer/Xcode/DerivedData/XSTests-cmkzjtilcohrtgdkssdfsfinnpne/Build/Intermediates"
export SRCROOT="/Users/xinsun/Documents/iOS/XSTests"
